epochs: 10000
batch_size: 4
num_workers: 4
learning_rate: 0.0001

criterion_type: L1Loss
scheduler_cfg:
  step_size: 10000
  gamma: 0.1

dataset_cfg:
  kpn_transform_kwargs:
    burst_num: 8
    downsample: 1
    blind: true
    misalignment: 2
    resize: 128
    max_translational_shift: 10
  base_dataset_cfg:
    train_ratio: 0.8
    random_split: false

model_cfg:
  burst_length: 8
  kernel_size: 5
