batch_size: 2
num_workers: 0
learning_rate: 0.0001
scheduler_cfg:
  step_size: 10
  gamma: 0.1
dataset_cfg:
  kpn_transform_kwargs:
    burst_num: 8
    downsample: 1
    blind: true
    misalignment: 2
    resize: 180
    max_translational_shift: 10
  base_dataset_cfg:
    train_ratio: 0.5
    random_split: false
model_cfg:
  burst_length: 8
  kernel_size: 5
